FROM golang as builder
WORKDIR /sources
COPY . .
RUN go env -w GO111MODULE=on && \
    go env -w GOPROXY=https://goproxy.cn,direct && \
    go build

FROM ubuntu
WORKDIR /usr/local/static
COPY --from=builder /sources/static .
RUN apt-get -y update && apt-get install -y
CMD ["/usr/local/static/static", "generate", "index"]
